const raw = [
  [
    { current: { innerText: "myLabel1", colspan: null } },
    { current: { innerText: "myLabel2", colspan: "2" } },
    { current: { innerText: "myLabel2", colspan: "2" } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    { current: { innerText: "myLabel2", colspan: null } },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    { current: { innerText: "myLabel1", colspan: "2" } },
    { current: { innerText: "myLabel1", colspan: "2" } },
    { current: { innerText: "myLabel1", colspan: "5" } },
    { current: { innerText: "myLabel1", colspan: "5" } },
    { current: { innerText: "myLabel1", colspan: "5" } },
    { current: { innerText: "myLabel1", colspan: "5" } },
    { current: { innerText: "myLabel1", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "5" } },
    { current: { innerText: "myLabel2", colspan: "2" } },
    { current: { innerText: "myLabel2", colspan: "2" } },
  ],
  [
    { current: { innerText: "myLabel2", colspan: "4" } },
    { current: { innerText: "myLabel2", colspan: "4" } },
    { current: { innerText: "myLabel2", colspan: "4" } },
    { current: { innerText: "myLabel2", colspan: "4" } },
    { current: { innerText: "myLabel3", colspan: "4" } },
    { current: { innerText: "myLabel3", colspan: "4" } },
    { current: { innerText: "myLabel3", colspan: "4" } },
    { current: { innerText: "myLabel3", colspan: "4" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
    { current: { innerText: "myLabel4", colspan: "6" } },
  ],
  [
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
    { current: { innerText: "myLabel1", colspan: "14" } },
  ],
  [
    { current: { innerText: "Gamalt ekki notað", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "-146580", colspan: null } },
    { current: { innerText: "-146580", colspan: null } },
    { current: { innerText: "-155772", colspan: null } },
    { current: { innerText: "-146580", colspan: null } },
    { current: { innerText: "-146580", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Skattar", colspan: null } },
    { current: { innerText: "-1079711", colspan: null } },
    { current: { innerText: "-1022849", colspan: null } },
    { current: { innerText: "-5880883", colspan: null } },
    { current: { innerText: "-2991679", colspan: null } },
    { current: { innerText: "144949", colspan: null } },
    { current: { innerText: "1571408", colspan: null } },
    { current: { innerText: "-4423417", colspan: null } },
    { current: { innerText: "-2960013", colspan: null } },
    { current: { innerText: "-2269630", colspan: null } },
    { current: { innerText: "18911825", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Afskriftir", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "-4715000", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Sérverk", colspan: null } },
    { current: { innerText: "39284029", colspan: null } },
    { current: { innerText: "35977158", colspan: null } },
    { current: { innerText: "32138595", colspan: null } },
    { current: { innerText: "30156737", colspan: null } },
    { current: { innerText: "38093535", colspan: null } },
    { current: { innerText: "37802881", colspan: null } },
    { current: { innerText: "48164048", colspan: null } },
    { current: { innerText: "31094323", colspan: null } },
    { current: { innerText: "30941126", colspan: null } },
    { current: { innerText: "25156326", colspan: null } },
    { current: { innerText: "32805", colspan: null } },
    { current: { innerText: "0", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Aðrar tekjur", colspan: null } },
    { current: { innerText: "3300025", colspan: null } },
    { current: { innerText: "2734444", colspan: null } },
    { current: { innerText: "4742304", colspan: null } },
    { current: { innerText: "3661721", colspan: null } },
    { current: { innerText: "6133374", colspan: null } },
    { current: { innerText: "4490036", colspan: null } },
    { current: { innerText: "5566064", colspan: null } },
    { current: { innerText: "6329577", colspan: null } },
    { current: { innerText: "2082485", colspan: null } },
    { current: { innerText: "5503459", colspan: null } },
    { current: { innerText: "1318545", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "KSV", colspan: null } },
    { current: { innerText: "-12463389", colspan: null } },
    { current: { innerText: "-7218201", colspan: null } },
    { current: { innerText: "-14977366", colspan: null } },
    { current: { innerText: "-8803117", colspan: null } },
    { current: { innerText: "-14600831", colspan: null } },
    { current: { innerText: "-13287948", colspan: null } },
    { current: { innerText: "-15585734", colspan: null } },
    { current: { innerText: "-10732213", colspan: null } },
    { current: { innerText: "-15927137", colspan: null } },
    { current: { innerText: "-15133530", colspan: null } },
    { current: { innerText: "-2337220", colspan: null } },
    { current: { innerText: "0", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Annar rekstur", colspan: null } },
    { current: { innerText: "-10587677", colspan: null } },
    { current: { innerText: "-11083554", colspan: null } },
    { current: { innerText: "-10254997", colspan: null } },
    { current: { innerText: "-9293821", colspan: null } },
    { current: { innerText: "-10911781", colspan: null } },
    { current: { innerText: "-8781532", colspan: null } },
    { current: { innerText: "-7135111", colspan: null } },
    { current: { innerText: "-9297675", colspan: null } },
    { current: { innerText: "-9953236", colspan: null } },
    { current: { innerText: "-10299057", colspan: null } },
    { current: { innerText: "-2058046", colspan: null } },
    { current: { innerText: "-577008", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Ræsting", colspan: null } },
    { current: { innerText: "207385787", colspan: null } },
    { current: { innerText: "209633281", colspan: null } },
    { current: { innerText: "212428881", colspan: null } },
    { current: { innerText: "211234537", colspan: null } },
    { current: { innerText: "214247872", colspan: null } },
    { current: { innerText: "199644435", colspan: null } },
    { current: { innerText: "183162382", colspan: null } },
    { current: { innerText: "212253892", colspan: null } },
    { current: { innerText: "228219004", colspan: null } },
    { current: { innerText: "232722005", colspan: null } },
    { current: { innerText: "184015308", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Fjármagnsliðir", colspan: null } },
    { current: { innerText: "-860766", colspan: null } },
    { current: { innerText: "-860589", colspan: null } },
    { current: { innerText: "-751003", colspan: null } },
    { current: { innerText: "-1446177", colspan: null } },
    { current: { innerText: "-59879", colspan: null } },
    { current: { innerText: "-893471", colspan: null } },
    { current: { innerText: "-895031", colspan: null } },
    { current: { innerText: "-1204764", colspan: null } },
    { current: { innerText: "-771422", colspan: null } },
    { current: { innerText: "-1015079", colspan: null } },
    { current: { innerText: "-4762511", colspan: null } },
    { current: { innerText: "", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Laun og lt. gjöld", colspan: null } },
    { current: { innerText: "-215944456", colspan: null } },
    { current: { innerText: "-219327419", colspan: null } },
    { current: { innerText: "-189219512", colspan: null } },
    { current: { innerText: "-205819873", colspan: null } },
    { current: { innerText: "-229179513", colspan: null } },
    { current: { innerText: "-222012348", colspan: null } },
    { current: { innerText: "-185595849", colspan: null } },
    { current: { innerText: "-209282334", colspan: null } },
    { current: { innerText: "-218381088", colspan: null } },
    { current: { innerText: "-214373944", colspan: null } },
    { current: { innerText: "-250006", colspan: null } },
    { current: { innerText: "-205304", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Tekjur samtals", colspan: null } },
    { current: { innerText: "249969841", colspan: null } },
    { current: { innerText: "248344883", colspan: null } },
    { current: { innerText: "249309780", colspan: null } },
    { current: { innerText: "245052995", colspan: null } },
    { current: { innerText: "258474781", colspan: null } },
    { current: { innerText: "241937352", colspan: null } },
    { current: { innerText: "236892494", colspan: null } },
    { current: { innerText: "249677792", colspan: null } },
    { current: { innerText: "261242615", colspan: null } },
    { current: { innerText: "263381790", colspan: null } },
    { current: { innerText: "185366658", colspan: null } },
    { current: { innerText: "0", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Rekstrarkostnaður samtals", colspan: null } },
    { current: { innerText: "-238995522", colspan: null } },
    { current: { innerText: "-237629174", colspan: null } },
    { current: { innerText: "-214451875", colspan: null } },
    { current: { innerText: "-223916811", colspan: null } },
    { current: { innerText: "-254692125", colspan: null } },
    { current: { innerText: "-244081828", colspan: null } },
    { current: { innerText: "-208316694", colspan: null } },
    { current: { innerText: "-229312222", colspan: null } },
    { current: { innerText: "-244261461", colspan: null } },
    { current: { innerText: "-239806531", colspan: null } },
    { current: { innerText: "-4645272", colspan: null } },
    { current: { innerText: "-782312", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "EBITDA", colspan: null } },
    { current: { innerText: "10974319", colspan: null } },
    { current: { innerText: "10715709", colspan: null } },
    { current: { innerText: "34857905", colspan: null } },
    { current: { innerText: "21136184", colspan: null } },
    { current: { innerText: "3782656", colspan: null } },
    { current: { innerText: "-2144476", colspan: null } },
    { current: { innerText: "28575800", colspan: null } },
    { current: { innerText: "20365570", colspan: null } },
    { current: { innerText: "16981154", colspan: null } },
    { current: { innerText: "23575259", colspan: null } },
    { current: { innerText: "180721386", colspan: null } },
    { current: { innerText: "-782312", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [
    { current: { innerText: "Hagnaður / Tap", colspan: null } },
    { current: { innerText: "4318842", colspan: null } },
    { current: { innerText: "4117271", colspan: null } },
    { current: { innerText: "23511019", colspan: null } },
    { current: { innerText: "11983328", colspan: null } },
    { current: { innerText: "-847274", colspan: null } },
    { current: { innerText: "-6181539", colspan: null } },
    { current: { innerText: "18542352", colspan: null } },
    { current: { innerText: "11485793", colspan: null } },
    { current: { innerText: "9225102", colspan: null } },
    { current: { innerText: "36757005", colspan: null } },
    { current: { innerText: "171243875", colspan: null } },
    { current: { innerText: "-5497312", colspan: null } },
    { current: { innerText: "34567", colspan: null } },
  ],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];

export default raw.map((el) => {
  return el.map((insideElement) => {
    if (insideElement?.current) {
      insideElement.current.getAttribute = function (value) {
        if (value != "data-colspan") return null;
        return this.colspan;
      }.bind(insideElement.current);

      return insideElement;
    } else {
      return null;
    }
  });
});
