export const sample1 = [
  {
    w: 10,
    h: 9,
    x: 0,
    y: 0,
    i: "a83c0c8e-4ed3-4473-8bde-1d46481c3921",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [],
      colors: [],
      isStacked: false,
      fillOpacity: [],
      strokeWidth: [],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 11,
    h: 5,
    x: 10,
    y: 0,
    i: "d21bbc61-b6ff-4da3-8c1c-8cf729424412",
    moved: false,
    static: false,
    widget: {
      type: "Bar",
      title: "My New Bar chart",
      yaxis: [],
      colors: [],
      isStacked: false,
      fillOpacity: [],
      strokeWidth: [],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 11,
    h: 6,
    x: 10,
    y: 5,
    i: "c21e5bff-9a5c-434b-963c-ea40bd6fa7d6",
    minW: 5,
    minH: 6,
    moved: false,
    static: false,
    widget: {
      type: "Pie",
      title: "My New Pie Chart",
      touch: 0,
      colors: [],
      selected_kpi_entries: [],
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 10,
    h: 12,
    x: 0,
    y: 9,
    i: "af89b7ef-c613-47ba-90ff-9151ce27ae6a",
    moved: false,
    static: false,
    widget: {
      type: "Gauge",
      colors: ["#3f90f4", "#3f90f4"],
      compareTo: "budget",
      needleType: "classic",
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 21,
    h: 4,
    x: 0,
    y: 21,
    i: "f17aa0db-0d3e-47c3-9388-a0b9b579faaf",
    moved: false,
    static: false,
    widget: {
      type: "none",
    },
  },
];

export const sample2 = [
  {
    w: 10,
    h: 11,
    x: 0,
    y: 0,
    i: "a83c0c8e-4ed3-4473-8bde-1d46481c3921",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [],
      colors: [],
      isStacked: false,
      fillOpacity: [],
      strokeWidth: [],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 9,
    h: 5,
    x: 10,
    y: 0,
    i: "d21bbc61-b6ff-4da3-8c1c-8cf729424412",
    moved: false,
    static: false,
    widget: {
      type: "Bar",
      title: "My New Bar chart",
      yaxis: [],
      colors: [],
      isStacked: false,
      fillOpacity: [],
      strokeWidth: [],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 9,
    h: 6,
    x: 12,
    y: 5,
    i: "c21e5bff-9a5c-434b-963c-ea40bd6fa7d6",
    minW: 5,
    minH: 6,
    moved: false,
    static: false,
    widget: {
      type: "Pie",
      title: "My New Pie Chart",
      touch: 0,
      colors: [],
      selected_kpi_entries: [],
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 10,
    h: 12,
    x: 0,
    y: 11,
    i: "af89b7ef-c613-47ba-90ff-9151ce27ae6a",
    moved: false,
    static: false,
    widget: {
      type: "Gauge",
      colors: ["#3f90f4", "#3f90f4"],
      compareTo: "budget",
      needleType: "classic",
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 21,
    h: 4,
    x: 0,
    y: 23,
    i: "c0c7083f-127f-4631-8ea2-e50833d5eede",
    moved: false,
    static: false,
    widget: {
      type: "none",
    },
  },
];

export const sample3 = [
  {
    rowId: 0,
    rowNumber: 1,
    columns: [
      {
        columnId: 0,
        columnNumber: 1,
        data: [
          {
            w: 10,
            h: 11,
            x: 0,
            y: 0,
            i: "a83c0c8e-4ed3-4473-8bde-1d46481c3921",
            minW: 4,
            minH: 5,
            moved: false,
            static: false,
            widget: {
              type: "Chart",
              title: "My New Chart",
              yaxis: [],
              colors: [],
              isStacked: false,
              fillOpacity: [],
              strokeWidth: [],
            },
            styles: {
              borderColor: "#000",
              borderStyle: "unset",
              borderWidth: 1,
              borderRadius: 0,
              backgroundColor: "#ffffff",
            },
          },
        ],
        width: 0.5,
      },
      {
        columnId: 10,
        columnNumber: 2,
        data: [
          {
            w: 9,
            h: 5,
            x: 10,
            y: 0,
            i: "d21bbc61-b6ff-4da3-8c1c-8cf729424412",
            moved: false,
            static: false,
            widget: {
              type: "Bar",
              title: "My New Bar chart",
              yaxis: [],
              colors: [],
              isStacked: false,
              fillOpacity: [],
              strokeWidth: [],
            },
            styles: {
              borderColor: "#000",
              borderStyle: "unset",
              borderWidth: 1,
              borderRadius: 0,
              backgroundColor: "#ffffff",
            },
          },
          {
            w: 9,
            h: 6,
            x: 10,
            y: 5,
            i: "c21e5bff-9a5c-434b-963c-ea40bd6fa7d6",
            minW: 5,
            minH: 6,
            moved: false,
            static: false,
            widget: {
              type: "Pie",
              title: "My New Pie Chart",
              touch: 0,
              colors: [],
              selected_kpi_entries: [],
            },
            styles: {
              boxShadow: "none",
              borderColor: "#000",
              borderStyle: "unset",
              borderWidth: 1,
              borderRadius: 0,
              backgroundColor: "#ffffff",
            },
          },
        ],
        width: 0.5,
      },
    ],
  },
  {
    rowId: 11,
    rowNumber: 2,
    columns: [
      {
        columnId: 0,
        columnNumber: 1,
        data: [
          {
            w: 10,
            h: 12,
            x: 0,
            y: 11,
            i: "af89b7ef-c613-47ba-90ff-9151ce27ae6a",
            moved: false,
            static: false,
            widget: {
              type: "Gauge",
              colors: ["#3f90f4", "#3f90f4"],
              compareTo: "budget",
              needleType: "classic",
            },
            styles: {
              boxShadow: "none",
              borderColor: "#000",
              borderStyle: "unset",
              borderWidth: 1,
              borderRadius: 0,
              backgroundColor: "#ffffff",
            },
          },
        ],
        width: 1,
      },
    ],
  },
  {
    rowId: 23,
    rowNumber: 3,
    columns: [
      {
        columnId: 0,
        columnNumber: 1,
        data: [
          {
            w: 21,
            h: 4,
            x: 0,
            y: 23,
            i: "c0c7083f-127f-4631-8ea2-e50833d5eede",
            moved: false,
            static: false,
            widget: {
              type: "none",
            },
          },
        ],
        width: 1,
      },
    ],
  },
];

export const sample4 = [
  {
    w: 10,
    h: 7,
    x: 0,
    y: 0,
    i: "fa8d50b1-e689-4874-be3e-3003a8f3835f",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#008FFB",
            },
          },
          labels: {
            style: {
              colors: "#008FFB",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#008FFB",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
        },
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#00E396",
            },
          },
          labels: {
            style: {
              colors: "#00E396",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#00E396",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
        },
      ],
      colors: ["#008FFB", "#00E396"],
      isStacked: false,
      fillOpacity: [0.7, 0.7],
      strokeWidth: [1, 1],
      selected_kpi_entries: [
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
            entryId: "169",
            usePlan: false,
            targetDim: null,
            yearCount: -2,
            targetColumn: "transientTotal",
          },
        },
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
            entryId: "175",
            usePlan: false,
            targetDim: null,
            yearCount: null,
            targetColumn: "transientTotal",
          },
        },
      ],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 10,
    h: 9,
    x: 0,
    y: 12,
    i: "daf0a2a7-afe5-4555-8601-b8ba0a2529d7",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#008FFB",
            },
          },
          labels: {
            style: {
              colors: "#008FFB",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#008FFB",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
        },
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#00E396",
            },
          },
          labels: {
            style: {
              colors: "#00E396",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#00E396",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
        },
      ],
      colors: ["#008FFB", "#00E396"],
      isStacked: false,
      fillOpacity: [0.7, 0.7],
      strokeWidth: [1, 1],
      selected_kpi_entries: [
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
            entryId: "169",
            usePlan: false,
            targetDim: null,
            yearCount: -2,
            targetColumn: "transientTotal",
          },
        },
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
            entryId: "175",
            usePlan: false,
            targetDim: null,
            yearCount: null,
            targetColumn: "transientTotal",
          },
        },
      ],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 10,
    h: 7,
    x: 11,
    y: 12,
    i: "cdcbfdcb-c9c3-41c7-92b6-d2843225435a",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#008FFB",
            },
          },
          labels: {
            style: {
              colors: "#008FFB",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#008FFB",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
        },
        {
          min: 0,
          show: false,
          title: {
            text: "",
            style: {
              color: "#00E396",
            },
          },
          labels: {
            style: {
              colors: "#00E396",
            },
          },
          opposite: false,
          reversed: false,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: "#00E396",
          },
          forceNiceScale: true,
          mainAxisPosition: "left",
          selectedKpiEntryUuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
        },
      ],
      colors: ["#008FFB", "#00E396"],
      isStacked: false,
      fillOpacity: [0.7, 0.7],
      strokeWidth: [1, 1],
      selected_kpi_entries: [
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "8c5ed5bc-f331-4d19-a6e5-5e78afae23c9",
            entryId: "169",
            usePlan: false,
            targetDim: null,
            yearCount: -2,
            targetColumn: "transientTotal",
          },
        },
        {
          type: "bar",
          inverted: false,
          setupItem: {
            uuid: "a250b912-b803-47fe-ba7c-fe24dcda8a0d",
            entryId: "175",
            usePlan: false,
            targetDim: null,
            yearCount: null,
            targetColumn: "transientTotal",
          },
        },
      ],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 10,
    h: 7,
    x: 10,
    y: 0,
    i: "b4ccd00d-482e-44a8-93ed-f361b9926b3e",
    minW: 4,
    minH: 5,
    moved: false,
    static: false,
    widget: {
      type: "Chart",
      title: "My New Chart",
      yaxis: [],
      colors: [],
      isStacked: false,
      fillOpacity: [],
      strokeWidth: [],
    },
    styles: {
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 21,
    h: 2,
    x: 0,
    y: 7,
    i: "93cbb283-923e-414d-98fa-b2ea4724df36",
    moved: false,
    static: false,
    widget: {
      type: "Title",
      title: "Kostnaður",
      styles: {},
    },
    styles: {
      color: "#262626",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 4,
    h: 3,
    x: 1,
    y: 9,
    i: "bdab954a-5a58-4cca-9362-bd9e0437fc7f",
    minW: 3,
    minH: 2,
    moved: false,
    static: false,
    widget: {
      type: "KpiCard",
      level: 1,
      title: "",
      kpi_entry: {
        uuid: "85738bf7-dd92-4f1a-91ab-e2b95d13e6ee",
        entryId: "184",
        usePlan: false,
        targetDim: null,
        yearCount: null,
        targetColumn: "transientTotal",
      },
      description: "-47.879.367",
    },
    styles: {
      boxShadow: "0 4px 12px #0000001a",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 4,
    h: 3,
    x: 5,
    y: 9,
    i: "a2313985-6def-43bb-875d-21b3f43acbcb",
    minW: 3,
    minH: 2,
    moved: false,
    static: false,
    widget: {
      type: "KpiCard",
      level: 1,
      title: "",
      kpi_entry: {
        uuid: "85738bf7-dd92-4f1a-91ab-e2b95d13e6ee",
        entryId: "184",
        usePlan: false,
        targetDim: null,
        yearCount: null,
        targetColumn: "transientTotal",
      },
      description: "-47.879.367",
    },
    styles: {
      boxShadow: "0 4px 12px #0000001a",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 4,
    h: 3,
    x: 12,
    y: 9,
    i: "3990adc6-b76c-4e6b-976c-be35e34943aa",
    minW: 3,
    minH: 2,
    moved: false,
    static: false,
    widget: {
      type: "KpiCard",
      level: 1,
      title: "",
      kpi_entry: {
        uuid: "85738bf7-dd92-4f1a-91ab-e2b95d13e6ee",
        entryId: "184",
        usePlan: false,
        targetDim: null,
        yearCount: null,
        targetColumn: "transientTotal",
      },
      description: "-47.879.367",
    },
    styles: {
      boxShadow: "0 4px 12px #0000001a",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 4,
    h: 3,
    x: 16,
    y: 9,
    i: "bfde15b0-703e-43d3-8aaa-e7bb34f3b3a7",
    minW: 3,
    minH: 2,
    moved: false,
    static: false,
    widget: {
      type: "KpiCard",
      level: 1,
      title: "",
      kpi_entry: {
        uuid: "85738bf7-dd92-4f1a-91ab-e2b95d13e6ee",
        entryId: "184",
        usePlan: false,
        targetDim: null,
        yearCount: null,
        targetColumn: "transientTotal",
      },
      description: "-47.879.367",
    },
    styles: {
      boxShadow: "0 4px 12px #0000001a",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 6,
    h: 6,
    x: 11,
    y: 19,
    i: "c197fe66-3b6a-4a1a-9f1a-9d18e9e9e872",
    moved: false,
    static: false,
    widget: {
      type: "Donut",
      title: "My New Donut Chart",
      touch: 0,
      colors: [],
      selected_kpi_entries: [],
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 6,
    h: 10,
    x: 4,
    y: 21,
    i: "9ff2ed8a-1a93-4522-b65f-be864ab5192d",
    minW: 5,
    minH: 6,
    moved: false,
    static: false,
    widget: {
      type: "Donut",
      title: "My New Donut Chart",
      touch: 0,
      colors: [],
      selected_kpi_entries: [],
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 6,
    h: 8,
    x: 11,
    y: 25,
    i: "bb12149e-450e-41be-a071-4f18773737ea",
    moved: false,
    static: false,
    widget: {
      type: "Donut",
      title: "My New Donut Chart",
      touch: 0,
      colors: [],
      selected_kpi_entries: [],
    },
    styles: {
      boxShadow: "none",
      borderColor: "#000",
      borderStyle: "unset",
      borderWidth: 1,
      borderRadius: 0,
      backgroundColor: "#ffffff",
    },
  },
  {
    w: 21,
    h: 4,
    x: 0,
    y: 33,
    i: "d967889b-c183-441b-a905-c53c0e86c60b",
    moved: false,
    static: false,
    widget: {
      type: "none",
    },
  },
];
